sonar.projectKey=homebox-client
sonar.projectName=homebox-client

sonar.sources=src
sonar.exclusions=node_modules/**,dist/**,public/**,**/*.test.*,**/*.spec.*

sonar.javascript.file.suffixes=.js,.jsx,.cjs,.mjs
sonar.typescript.file.suffixes=.ts,.tsx,.cts,.mts
sonar.typescript.tsconfigPath=tsconfig.app.json
