sonar.projectKey=com.moujitx.homebox.client
sonar.projectName=Homebox Client

sonar.sources=src
sonar.exclusions=node_modules/**,dist/**,public/**,**/*.test.*,**/*.spec.*

sonar.javascript.file.suffixes=.js,.jsx,.ts,.tsx
sonar.typescript.tsconfigPath=tsconfig.app.json
